---
resources:
  - name: fauna-python-repository
    type: git
    icon: github
    source:
      uri: https://github.com/fauna/faunadb-python
      branch: release-4.1.1

  - name: fauna-python-repository-docs
    type: git
    icon: github
    source:
      uri: git@github.com:parkhomenko/faunadb-python.git
      branch: gh-pages
      private_key: ((repo_key))

jobs:
  - name: release
    serial: true
    public: false
    plan:
      - get: fauna-python-repository
      - get: fauna-python-repository-docs

      - task: integration-tests
        file: fauna-python-repository/concourse/tasks/integration-tests.yml
        privileged: true
        params:
          FAUNA_ROOT_KEY: ((fauna.secret))
          FAUNA_DOMAIN: ((fauna.domain))
          FAUNA_SCHEME: ((fauna.scheme))
          FAUNA_PORT: ((fauna.port))

      - task: build
        file: fauna-python-repository/concourse/tasks/build.yml

#      - task: publish
#        file: fauna-python-repository/concourse/tasks/publish.yml
#        params:
#          TWINE_USERNAME: ((fauna/twine.username))
#          TWINE_PASSWORD: ((fauna/twine.password))

      - task: publish-docs
        file: fauna-python-repository/concourse/tasks/publish-docs.yml

      - put: fauna-python-repository-docs
        params:
          repository: fauna-python-repository-updated-docs
