---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: python
    tag: 3.9.14-alpine3.16

inputs:
  - name: fauna-python-repository

outputs:
  - name: fauna-python-repository/dist

run:
  path: ./fauna-python-repository/concourse/scripts/build.sh
