---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: python
    tag: 3.9.5-alpine3.13

params:
  TWINE_USERNAME:
  TWINE_PASSWORD:

inputs:
  - name: fauna-python-repository
  - name: fauna-python-repository/dist

run:
  path: ./fauna-python-repository/concourse/scripts/publish.sh
